### ISSUE TITLE
atom stops building with snapcraft 2.14

### ISSUE THREAD

**Issue by dholbach** [ubuntu/snappy-playpen#207]
Applying the following diff for 2.14
```diff
diff --git a/atom/snapcraft.yaml b/atom/snapcraft.yaml
index 0f98a5a..21179d2 100644
--- a/atom/snapcraft.yaml
+++ b/atom/snapcraft.yaml
@@ -33,6 +33,6 @@ parts:
       - unity-gtk2-module
   atom-copy:
     source: .
-    plugin: copy
-    files:
+    plugin: dump
+    organize:
       wrapper: bin/wrapper
```

I get the following during the build:
```
...
/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/grunt --gruntfile /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/build/Gruntfile.coffee install --install-dir /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install
Running "install" task

Done, without errors.


Execution Time (2016-08-10 05:08:22 UTC)
loading tasks  5.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 76%
install        1.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 24%
Total 6.9s

Parts 'atom-copy' and 'atom' have the following file paths in common which have different contents:
README.md
```

**Comment by dholbach** [comment]
It fails differently now:
```
Pulling atom 
Downloading 'v1.8.0.tar.gz'[====================================================================================================================] 100%
Downloading 'node-v4.4.4-linux-x64.tar.gz'[=====================================================================================================] 100%
npm --cache-min=Infinity install

> atom@1.8.0 preinstall /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build
> node -e 'process.exit(0)'

 
> cached-run-in-this-context@0.4.1 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/cached-run-in-this-context
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/cached-run-in-this-context
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> scrollbar-style@3.2.0 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/scrollbar-style
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/scrollbar-style
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> nslog@3.0.0 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/nslog
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/nslog
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> runas@3.1.1 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/runas
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/runas
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> keyboard-layout@1.3.1 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/atom-keymap/node_modules/keyboard-layout
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/atom-keymap/node_modules/keyboard-layout
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> pathwatcher@6.7.1 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/text-buffer/node_modules/pathwatcher
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/text-buffer/node_modules/pathwatcher
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> marker-index@3.1.0 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/text-buffer/node_modules/marker-index
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/text-buffer/node_modules/marker-index
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> oniguruma@5.1.2 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/oniguruma
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/oniguruma
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> pathwatcher@6.2.5 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/pathwatcher
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/pathwatcher
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> git-utils@4.1.2 install /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/git-utils
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v4.4.4/node-v4.4.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.8.0-26-generic
gyp ERR! command "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/node_modules/git-utils
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.8.0-26-generic
npm ERR! argv "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/node" "/home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/install/bin/npm" "--cache-min=Infinity" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cached-run-in-this-context@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cached-run-in-this-context@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cached-run-in-this-context package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cached-run-in-this-context
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls cached-run-in-this-context
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daniel/dev/snappy/snappy-playpen/atom/parts/atom/build/npm-debug.log
Command '['/bin/sh', '/tmp/tmp2b4_h6hk', 'npm', '--cache-min=Infinity', 'install']' returned non-zero exit status 1
```
